services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always

        ports:
            - "5432:5432"

        env_file:
            - ./.env

        environment :
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: manga-reader

        volumes:
            - /var/db/postgres/manga-reader

volumes:
    postgres:
        name: db